[package]
name = "rust-forge-gym"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
askama = { version = "0.15.6", features = ["derive"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "sqlite",
    "macros",
    "migrate"
]}
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["fs", "trace"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenv = "0.15.0"
serde_json = "1.0.149"
regex = "1.12.3"
rayon = "1.12.0"
pulldown-cmark = "0.13.3"
parking_lot = "0.12.5"
oqueue = "0.1.9"
thiserror = "2.0.18"
num_cpus = "1.17.0"
remain = "0.2.15"
http = "1.4.0"
clap = { version = "4.5", features = ["derive"] }
rand = { version = "0.10.1", features = ["std_rng"] }
fastrand = "2.4.1"
